/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

public enum CAIceState_t {
  CAIceState_None,
  CAIceState_Failed,
  CAIceState_GatheringDone,
  CAIceState_Connected,
  CAIceState_Teminated
}

}
