/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

public enum CAMediaType_t {
  CAMediaType_None = 0x00,
  CAMediaType_Audio = (0x01 << 0),
  CAMediaType_Video = (0x01 << 1),
  CAMediaType_ScreenCast = (0x01 << 2),
  CAMediaType_AudioVideo = (CAMediaType_Audio|CAMediaType_Video),
  CAMediaType_All = 0xFF
}

}
