/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CASignalingCallbackObj : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CASignalingCallbackObj(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CASignalingCallbackObj obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CASignalingCallbackObj() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CASignalingCallbackObj(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CASignalingCallbackObj(CASignalingCallback obj) : this(clWRAPPINVOKE.new_CASignalingCallbackObj__SWIG_0(CASignalingCallback.getCPtr(obj)), true) {
  }

  public CASignalingCallbackObj(CASignalingCallbackObj obj) : this(clWRAPPINVOKE.new_CASignalingCallbackObj__SWIG_1(CASignalingCallbackObj.getCPtr(obj)), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CASignalingCallback unWrap() {
    IntPtr cPtr = clWRAPPINVOKE.CASignalingCallbackObj_unWrap(swigCPtr);
    CASignalingCallback ret = (cPtr == IntPtr.Zero) ? null : new CASignalingCallback(cPtr, false);
    return ret;
  }

}

}
