/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CASignalingObj : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CASignalingObj(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CASignalingObj obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CASignalingObj() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CASignalingObj(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CASignalingObj(CASignaling obj) : this(clWRAPPINVOKE.new_CASignalingObj__SWIG_0(CASignaling.getCPtr(obj)), true) {
  }

  public CASignalingObj() : this(clWRAPPINVOKE.new_CASignalingObj__SWIG_1(), true) {
  }

  public CASignalingObj(CASignalingObj obj) : this(clWRAPPINVOKE.new_CASignalingObj__SWIG_2(CASignalingObj.getCPtr(obj)), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CASignaling unWrap() {
    IntPtr cPtr = clWRAPPINVOKE.CASignalingObj_unWrap(swigCPtr);
    CASignaling ret = (cPtr == IntPtr.Zero) ? null : new CASignaling(cPtr, false);
    return ret;
  }

}

}
