/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CASignalingCallEvent : CASignalingEvent {
  private HandleRef swigCPtr;

  internal CASignalingCallEvent(IntPtr cPtr, bool cMemoryOwn) : base(clWRAPPINVOKE.CASignalingCallEvent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CASignalingCallEvent obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CASignalingCallEvent() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CASignalingCallEvent(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public CASignalingCallEvent(string strDescription) : this(clWRAPPINVOKE.new_CASignalingCallEvent(strDescription), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string getObjectId() {
    string ret = clWRAPPINVOKE.CASignalingCallEvent_getObjectId(swigCPtr);
    return ret;
  }

  public string getType() {
    string ret = clWRAPPINVOKE.CASignalingCallEvent_getType(swigCPtr);
    return ret;
  }

  public string getFrom() {
    string ret = clWRAPPINVOKE.CASignalingCallEvent_getFrom(swigCPtr);
    return ret;
  }

  public string getTo() {
    string ret = clWRAPPINVOKE.CASignalingCallEvent_getTo(swigCPtr);
    return ret;
  }

  public string getCallId() {
    string ret = clWRAPPINVOKE.CASignalingCallEvent_getCallId(swigCPtr);
    return ret;
  }

  public string getTransacId() {
    string ret = clWRAPPINVOKE.CASignalingCallEvent_getTransacId(swigCPtr);
    return ret;
  }

  public string getSdp() {
    string ret = clWRAPPINVOKE.CASignalingCallEvent_getSdp(swigCPtr);
    return ret;
  }

}

}
