/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CASignalingEvent : CAObj {
  private HandleRef swigCPtr;

  internal CASignalingEvent(IntPtr cPtr, bool cMemoryOwn) : base(clWRAPPINVOKE.CASignalingEvent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CASignalingEvent obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CASignalingEvent() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CASignalingEvent(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public CASignalingEvent(CASignalingEventType_t eType, string strDescription, IntPtr pcDataPtr, uint nDataSize) : this(clWRAPPINVOKE.new_CASignalingEvent__SWIG_0((int)eType, strDescription, pcDataPtr, nDataSize), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CASignalingEvent(CASignalingEventType_t eType, string strDescription, IntPtr pcDataPtr) : this(clWRAPPINVOKE.new_CASignalingEvent__SWIG_1((int)eType, strDescription, pcDataPtr), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CASignalingEvent(CASignalingEventType_t eType, string strDescription) : this(clWRAPPINVOKE.new_CASignalingEvent__SWIG_2((int)eType, strDescription), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public override string getObjectId() {
    string ret = clWRAPPINVOKE.CASignalingEvent_getObjectId(swigCPtr);
    return ret;
  }

  public virtual CASignalingEventType_t getType() {
    CASignalingEventType_t ret = (CASignalingEventType_t)clWRAPPINVOKE.CASignalingEvent_getType(swigCPtr);
    return ret;
  }

  public virtual string getDescription() {
    string ret = clWRAPPINVOKE.CASignalingEvent_getDescription(swigCPtr);
    return ret;
  }

  public virtual IntPtr getDataPtr() { return clWRAPPINVOKE.CASignalingEvent_getDataPtr(swigCPtr); }

  public virtual uint getDataSize() {
    uint ret = clWRAPPINVOKE.CASignalingEvent_getDataSize(swigCPtr);
    return ret;
  }

}

}
