/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public enum CADebugLevel_t {
  CADebugLevel_Info(4),
  CADebugLevel_Warn(3),
  CADebugLevel_Error(2),
  CADebugLevel_Fatal(1);

  public final int swigValue() {
    return swigValue;
  }

  public static CADebugLevel_t swigToEnum(int swigValue) {
    CADebugLevel_t[] swigValues = CADebugLevel_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CADebugLevel_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CADebugLevel_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CADebugLevel_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CADebugLevel_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CADebugLevel_t(CADebugLevel_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

