/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASessionCall extends CASession {
  private long swigCPtr;

  protected CASessionCall(long cPtr, boolean cMemoryOwn) {
    super(clWRAPJNI.CASessionCall_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASessionCall obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASessionCall(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getObjectId() {
    return clWRAPJNI.CASessionCall_getObjectId(swigCPtr, this);
  }

  public boolean setIceCallback(CASessionCallIceCallbackObj oIceCallback) {
    return clWRAPJNI.CASessionCall_setIceCallback(swigCPtr, this, CASessionCallIceCallbackObj.getCPtr(oIceCallback), oIceCallback);
  }

  public boolean setVideoDisplays(CAMediaType_t eVideoType, long displayLocal, long displayRemote) {
    return clWRAPJNI.CASessionCall_setVideoDisplays__SWIG_0(swigCPtr, this, eVideoType.swigValue(), displayLocal, displayRemote);
  }

  public boolean setVideoDisplays(CAMediaType_t eVideoType, long displayLocal) {
    return clWRAPJNI.CASessionCall_setVideoDisplays__SWIG_1(swigCPtr, this, eVideoType.swigValue(), displayLocal);
  }

  public boolean setVideoDisplays(CAMediaType_t eVideoType) {
    return clWRAPJNI.CASessionCall_setVideoDisplays__SWIG_2(swigCPtr, this, eVideoType.swigValue());
  }

  public boolean call(CAMediaType_t eMediaType, String strDestUserId) {
    return clWRAPJNI.CASessionCall_call(swigCPtr, this, eMediaType.swigValue(), strDestUserId);
  }

  public boolean acceptEvent(CASignalingCallEventObj e) {
    return clWRAPJNI.CASessionCall_acceptEvent(swigCPtr, this, CASignalingCallEventObj.getCPtr(e), e);
  }

  public static boolean rejectEvent(CASignalingObj oSignaling, CASignalingCallEventObj e) {
    return clWRAPJNI.CASessionCall_rejectEvent(CASignalingObj.getCPtr(oSignaling), oSignaling, CASignalingCallEventObj.getCPtr(e), e);
  }

  public boolean setMute(boolean bMuted, CAMediaType_t eMediaType) {
    return clWRAPJNI.CASessionCall_setMute__SWIG_0(swigCPtr, this, bMuted, eMediaType.swigValue());
  }

  public boolean setMute(boolean bMuted) {
    return clWRAPJNI.CASessionCall_setMute__SWIG_1(swigCPtr, this, bMuted);
  }

  public boolean hangup() {
    return clWRAPJNI.CASessionCall_hangup(swigCPtr, this);
  }

  public boolean setVideoFps(int nFps, CAMediaType_t eMediaType) {
    return clWRAPJNI.CASessionCall_setVideoFps__SWIG_0(swigCPtr, this, nFps, eMediaType.swigValue());
  }

  public boolean setVideoFps(int nFps) {
    return clWRAPJNI.CASessionCall_setVideoFps__SWIG_1(swigCPtr, this, nFps);
  }

  public boolean setVideoBandwidthUploadMax(int nMax, CAMediaType_t eMediaType) {
    return clWRAPJNI.CASessionCall_setVideoBandwidthUploadMax__SWIG_0(swigCPtr, this, nMax, eMediaType.swigValue());
  }

  public boolean setVideoBandwidthUploadMax(int nMax) {
    return clWRAPJNI.CASessionCall_setVideoBandwidthUploadMax__SWIG_1(swigCPtr, this, nMax);
  }

  public boolean setVideoBandwidthDownloadMax(int nMax, CAMediaType_t eMediaType) {
    return clWRAPJNI.CASessionCall_setVideoBandwidthDownloadMax__SWIG_0(swigCPtr, this, nMax, eMediaType.swigValue());
  }

  public boolean setVideoBandwidthDownloadMax(int nMax) {
    return clWRAPJNI.CASessionCall_setVideoBandwidthDownloadMax__SWIG_1(swigCPtr, this, nMax);
  }

  public String getCallId() {
    return clWRAPJNI.CASessionCall_getCallId(swigCPtr, this);
  }

  public CAMediaType_t getMediaType() {
    return CAMediaType_t.swigToEnum(clWRAPJNI.CASessionCall_getMediaType(swigCPtr, this));
  }

  public CAIceState_t getIceState() {
    return CAIceState_t.swigToEnum(clWRAPJNI.CASessionCall_getIceState(swigCPtr, this));
  }

  public static CASessionCallObj newObj(CASignalingObj signalingSession) {
    return new CASessionCallObj(clWRAPJNI.CASessionCall_newObj__SWIG_0(CASignalingObj.getCPtr(signalingSession), signalingSession), true);
  }

  public static CASessionCallObj newObj(CASignalingObj signalingSession, CASignalingCallEventObj offer) {
    return new CASessionCallObj(clWRAPJNI.CASessionCall_newObj__SWIG_1(CASignalingObj.getCPtr(signalingSession), signalingSession, CASignalingCallEventObj.getCPtr(offer), offer), true);
  }

}
