/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASession extends CAObj {
  private long swigCPtr;

  protected CASession(long cPtr, boolean cMemoryOwn) {
    super(clWRAPJNI.CASession_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASession(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getObjectId() {
    return clWRAPJNI.CASession_getObjectId(swigCPtr, this);
  }

  public CASessionType_t getType() {
    return CASessionType_t.swigToEnum(clWRAPJNI.CASession_getType(swigCPtr, this));
  }

}
