/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASignalingEventObj {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CASignalingEventObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASignalingEventObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASignalingEventObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CASignalingEventObj(CASignalingEvent obj) {
    this(clWRAPJNI.new_CASignalingEventObj__SWIG_0(CASignalingEvent.getCPtr(obj), obj), true);
  }

  public CASignalingEventObj(CASignalingEventObj obj) {
    this(clWRAPJNI.new_CASignalingEventObj__SWIG_1(CASignalingEventObj.getCPtr(obj), obj), true);
  }

  public CASignalingEvent unWrap() {
    long cPtr = clWRAPJNI.CASignalingEventObj_unWrap(swigCPtr, this);
    return (cPtr == 0) ? null : new CASignalingEvent(cPtr, false);
  }

}
