/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CAEngine extends CAObj {
  private long swigCPtr;

  protected CAEngine(long cPtr, boolean cMemoryOwn) {
    super(clWRAPJNI.CAEngine_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CAEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CAEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getObjectId() {
    return clWRAPJNI.CAEngine_getObjectId(swigCPtr, this);
  }

  public static boolean init(String strCredUserId, String strCredPassword) {
    return clWRAPJNI.CAEngine_init__SWIG_0(strCredUserId, strCredPassword);
  }

  public static boolean init(String strCredUserId) {
    return clWRAPJNI.CAEngine_init__SWIG_1(strCredUserId);
  }

  public static boolean init() {
    return clWRAPJNI.CAEngine_init__SWIG_2();
  }

  public static boolean deInit() {
    return clWRAPJNI.CAEngine_deInit();
  }

  public static boolean isInitialized() {
    return clWRAPJNI.CAEngine_isInitialized();
  }

}
