/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public enum CAIceState_t {
  CAIceState_None,
  CAIceState_Failed,
  CAIceState_GatheringDone,
  CAIceState_Connected,
  CAIceState_Teminated;

  public final int swigValue() {
    return swigValue;
  }

  public static CAIceState_t swigToEnum(int swigValue) {
    CAIceState_t[] swigValues = CAIceState_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CAIceState_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CAIceState_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CAIceState_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CAIceState_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CAIceState_t(CAIceState_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

