/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASignalingCallbackObj {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CASignalingCallbackObj(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASignalingCallbackObj obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASignalingCallbackObj(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CASignalingCallbackObj(CASignalingCallback obj) {
    this(clWRAPJNI.new_CASignalingCallbackObj__SWIG_0(CASignalingCallback.getCPtr(obj), obj), true);
  }

  public CASignalingCallbackObj(CASignalingCallbackObj obj) {
    this(clWRAPJNI.new_CASignalingCallbackObj__SWIG_1(CASignalingCallbackObj.getCPtr(obj), obj), true);
  }

  public CASignalingCallback unWrap() {
    long cPtr = clWRAPJNI.CASignalingCallbackObj_unWrap(swigCPtr, this);
    return (cPtr == 0) ? null : new CASignalingCallback(cPtr, false);
  }

}
