# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package clWRAP;
use base qw(Exporter);
use base qw(DynaLoader);
package clWRAPc;
bootstrap clWRAP;
package clWRAP;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package clWRAP;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package clWRAP;


############# Class : clWRAP::CAObj ##############

package clWRAP::CAObj;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( clWRAP );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        clWRAPc::delete_CAObj($self);
        delete $OWNER{$self};
    }
}

*getObjectId = *clWRAPc::CAObj_getObjectId;
*takeRef = *clWRAPc::CAObj_takeRef;
*releaseRef = *clWRAPc::CAObj_releaseRef;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : clWRAP::CAEngine ##############

package clWRAP::CAEngine;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( clWRAP::CAObj clWRAP );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        clWRAPc::delete_CAEngine($self);
        delete $OWNER{$self};
    }
}

*getObjectId = *clWRAPc::CAEngine_getObjectId;
*init = *clWRAPc::CAEngine_init;
*deInit = *clWRAPc::CAEngine_deInit;
*isInitialized = *clWRAPc::CAEngine_isInitialized;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package clWRAP;

1;
