/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASessionCallIceCallback extends CAObj {
  private long swigCPtr;

  protected CASessionCallIceCallback(long cPtr, boolean cMemoryOwn) {
    super(clWRAPJNI.CASessionCallIceCallback_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASessionCallIceCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASessionCallIceCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean onStateChanged(CASessionCallObj oCall) {
    return clWRAPJNI.CASessionCallIceCallback_onStateChanged(swigCPtr, this, CASessionCallObj.getCPtr(oCall), oCall);
  }

}
