/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASignalingEvent extends CAObj {
  private long swigCPtr;

  protected CASignalingEvent(long cPtr, boolean cMemoryOwn) {
    super(clWRAPJNI.CASignalingEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASignalingEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASignalingEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CASignalingEvent(CASignalingEventType_t eType, String strDescription, java.nio.ByteBuffer pcDataPtr, long nDataSize) {
    this(clWRAPJNI.new_CASignalingEvent__SWIG_0(eType.swigValue(), strDescription, pcDataPtr, nDataSize), true);
  }

  public CASignalingEvent(CASignalingEventType_t eType, String strDescription, java.nio.ByteBuffer pcDataPtr) {
    this(clWRAPJNI.new_CASignalingEvent__SWIG_1(eType.swigValue(), strDescription, pcDataPtr), true);
  }

  public CASignalingEvent(CASignalingEventType_t eType, String strDescription) {
    this(clWRAPJNI.new_CASignalingEvent__SWIG_2(eType.swigValue(), strDescription), true);
  }

  public String getObjectId() {
    return clWRAPJNI.CASignalingEvent_getObjectId(swigCPtr, this);
  }

  public CASignalingEventType_t getType() {
    return CASignalingEventType_t.swigToEnum(clWRAPJNI.CASignalingEvent_getType(swigCPtr, this));
  }

  public String getDescription() {
    return clWRAPJNI.CASignalingEvent_getDescription(swigCPtr, this);
  }

  public java.nio.ByteBuffer getDataPtr() { return clWRAPJNI.CASignalingEvent_getDataPtr(swigCPtr, this); }

  public long getDataSize() {
    return clWRAPJNI.CASignalingEvent_getDataSize(swigCPtr, this);
  }

}
