/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

public enum CADebugLevel_t {
  CADebugLevel_Info = 4,
  CADebugLevel_Warn = 3,
  CADebugLevel_Error = 2,
  CADebugLevel_Fatal = 1
}

}
