/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CAEngine : CAObj {
  private HandleRef swigCPtr;

  internal CAEngine(IntPtr cPtr, bool cMemoryOwn) : base(clWRAPPINVOKE.CAEngine_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CAEngine obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CAEngine() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CAEngine(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override string getObjectId() {
    string ret = clWRAPPINVOKE.CAEngine_getObjectId(swigCPtr);
    return ret;
  }

  public static bool init(string strCredUserId, string strCredPassword) {
    bool ret = clWRAPPINVOKE.CAEngine_init__SWIG_0(strCredUserId, strCredPassword);
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool init(string strCredUserId) {
    bool ret = clWRAPPINVOKE.CAEngine_init__SWIG_1(strCredUserId);
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool init() {
    bool ret = clWRAPPINVOKE.CAEngine_init__SWIG_2();
    return ret;
  }

  public static bool deInit() {
    bool ret = clWRAPPINVOKE.CAEngine_deInit();
    return ret;
  }

  public static bool isInitialized() {
    bool ret = clWRAPPINVOKE.CAEngine_isInitialized();
    return ret;
  }

}

}
