/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CAObj : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CAObj(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CAObj obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CAObj() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CAObj(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual string getObjectId() {
    string ret = clWRAPPINVOKE.CAObj_getObjectId(swigCPtr);
    return ret;
  }

  public int takeRef() {
    int ret = clWRAPPINVOKE.CAObj_takeRef(swigCPtr);
    return ret;
  }

  public int releaseRef() {
    int ret = clWRAPPINVOKE.CAObj_releaseRef(swigCPtr);
    return ret;
  }

}

}
