/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CASessionCallObj : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CASessionCallObj(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CASessionCallObj obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CASessionCallObj() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CASessionCallObj(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CASessionCallObj(CASessionCall obj) : this(clWRAPPINVOKE.new_CASessionCallObj__SWIG_0(CASessionCall.getCPtr(obj)), true) {
  }

  public CASessionCallObj(CASessionCallObj obj) : this(clWRAPPINVOKE.new_CASessionCallObj__SWIG_1(CASessionCallObj.getCPtr(obj)), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CASessionCall unWrap() {
    IntPtr cPtr = clWRAPPINVOKE.CASessionCallObj_unWrap(swigCPtr);
    CASessionCall ret = (cPtr == IntPtr.Zero) ? null : new CASessionCall(cPtr, false);
    return ret;
  }

}

}
