/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CASignalingCallback : CAObj {
  private HandleRef swigCPtr;

  internal CASignalingCallback(IntPtr cPtr, bool cMemoryOwn) : base(clWRAPPINVOKE.CASignalingCallback_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CASignalingCallback obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CASignalingCallback() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CASignalingCallback(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual bool onEventNet(CASignalingEventObj e) {
    bool ret = clWRAPPINVOKE.CASignalingCallback_onEventNet(swigCPtr, CASignalingEventObj.getCPtr(e));
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool onEventCall(CASignalingCallEventObj e) {
    bool ret = clWRAPPINVOKE.CASignalingCallback_onEventCall(swigCPtr, CASignalingCallEventObj.getCPtr(e));
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
