/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

public enum CASignalingEventType_t {
  CASignalingEventType_NetConnected,
  CASignalingEventType_NetReady,
  CASignalingEventType_NetData,
  CASignalingEventType_NetDisconnected,
  CASignalingEventType_NetError,
  CASignalingEventType_Call
}

}
