/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.clWRAP {

using System;
using System.Runtime.InteropServices;

public class CASignalingEventObj : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CASignalingEventObj(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CASignalingEventObj obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CASignalingEventObj() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          clWRAPPINVOKE.delete_CASignalingEventObj(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CASignalingEventObj(CASignalingEvent obj) : this(clWRAPPINVOKE.new_CASignalingEventObj__SWIG_0(CASignalingEvent.getCPtr(obj)), true) {
  }

  public CASignalingEventObj(CASignalingEventObj obj) : this(clWRAPPINVOKE.new_CASignalingEventObj__SWIG_1(CASignalingEventObj.getCPtr(obj)), true) {
    if (clWRAPPINVOKE.SWIGPendingException.Pending) throw clWRAPPINVOKE.SWIGPendingException.Retrieve();
  }

  public CASignalingEvent unWrap() {
    IntPtr cPtr = clWRAPPINVOKE.CASignalingEventObj_unWrap(swigCPtr);
    CASignalingEvent ret = (cPtr == IntPtr.Zero) ? null : new CASignalingEvent(cPtr, false);
    return ret;
  }

}

}
