/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public enum CASessionType_t {
  CASessionType_None,
  CASessionType_Call;

  public final int swigValue() {
    return swigValue;
  }

  public static CASessionType_t swigToEnum(int swigValue) {
    CASessionType_t[] swigValues = CASessionType_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CASessionType_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CASessionType_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CASessionType_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CASessionType_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CASessionType_t(CASessionType_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

