/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASignalingCallEvent extends CASignalingEvent {
  private long swigCPtr;

  protected CASignalingCallEvent(long cPtr, boolean cMemoryOwn) {
    super(clWRAPJNI.CASignalingCallEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASignalingCallEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASignalingCallEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CASignalingCallEvent(String strDescription) {
    this(clWRAPJNI.new_CASignalingCallEvent(strDescription), true);
  }

  public String getObjectId() {
    return clWRAPJNI.CASignalingCallEvent_getObjectId(swigCPtr, this);
  }

  public String getType() {
    return clWRAPJNI.CASignalingCallEvent_getType(swigCPtr, this);
  }

  public String getFrom() {
    return clWRAPJNI.CASignalingCallEvent_getFrom(swigCPtr, this);
  }

  public String getTo() {
    return clWRAPJNI.CASignalingCallEvent_getTo(swigCPtr, this);
  }

  public String getCallId() {
    return clWRAPJNI.CASignalingCallEvent_getCallId(swigCPtr, this);
  }

  public String getTransacId() {
    return clWRAPJNI.CASignalingCallEvent_getTransacId(swigCPtr, this);
  }

  public String getSdp() {
    return clWRAPJNI.CASignalingCallEvent_getSdp(swigCPtr, this);
  }

}
