/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public class CASignaling extends CAObj {
  private long swigCPtr;

  protected CASignaling(long cPtr, boolean cMemoryOwn) {
    super(clWRAPJNI.CASignaling_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CASignaling obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        clWRAPJNI.delete_CASignaling(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String getObjectId() {
    return clWRAPJNI.CASignaling_getObjectId(swigCPtr, this);
  }

  public boolean setCallback(CASignalingCallbackObj oCallback) {
    return clWRAPJNI.CASignaling_setCallback(swigCPtr, this, CASignalingCallbackObj.getCPtr(oCallback), oCallback);
  }

  public boolean isConnected() {
    return clWRAPJNI.CASignaling_isConnected(swigCPtr, this);
  }

  public boolean isReady() {
    return clWRAPJNI.CASignaling_isReady(swigCPtr, this);
  }

  public boolean connect() {
    return clWRAPJNI.CASignaling_connect(swigCPtr, this);
  }

  public boolean sendData(java.nio.ByteBuffer pcData, long nDataSize) {
    return clWRAPJNI.CASignaling_sendData(swigCPtr, this, pcData, nDataSize);
  }

  public boolean disConnect() {
    return clWRAPJNI.CASignaling_disConnect(swigCPtr, this);
  }

  public static CASignalingObj newObj(String strConnectionUri, String strCredUserId, String strCredPassword, String pcLocalIP, int nLocalPort) {
    return new CASignalingObj(clWRAPJNI.CASignaling_newObj__SWIG_0(strConnectionUri, strCredUserId, strCredPassword, pcLocalIP, nLocalPort), true);
  }

  public static CASignalingObj newObj(String strConnectionUri, String strCredUserId, String strCredPassword, String pcLocalIP) {
    return new CASignalingObj(clWRAPJNI.CASignaling_newObj__SWIG_1(strConnectionUri, strCredUserId, strCredPassword, pcLocalIP), true);
  }

  public static CASignalingObj newObj(String strConnectionUri, String strCredUserId, String strCredPassword) {
    return new CASignalingObj(clWRAPJNI.CASignaling_newObj__SWIG_2(strConnectionUri, strCredUserId, strCredPassword), true);
  }

  public String getCredUserId() {
    return clWRAPJNI.CASignaling_getCredUserId(swigCPtr, this);
  }

  public String getCredPassword() {
    return clWRAPJNI.CASignaling_getCredPassword(swigCPtr, this);
  }

}
