/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.clWRAP;

public enum CASignalingEventType_t {
  CASignalingEventType_NetConnected,
  CASignalingEventType_NetReady,
  CASignalingEventType_NetData,
  CASignalingEventType_NetDisconnected,
  CASignalingEventType_NetError,
  CASignalingEventType_Call;

  public final int swigValue() {
    return swigValue;
  }

  public static CASignalingEventType_t swigToEnum(int swigValue) {
    CASignalingEventType_t[] swigValues = CASignalingEventType_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (CASignalingEventType_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + CASignalingEventType_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private CASignalingEventType_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private CASignalingEventType_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private CASignalingEventType_t(CASignalingEventType_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

